AllCops:
  NewCops: enable
  Exclude:
    - "db/**/*"
    - "bin/*" 
    - "config/**/*"
    - "Guardfile"
    - "Rakefile"
    - "node_modules/**/*"

  DisplayCopNames: true

Style/Documentation:
  Enabled: false
Layout/LineLength:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
Metrics/ParameterLists:
  Enabled: false
Style/GuardClause:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Metrics/MethodLength:
  Max: 1000000
Metrics/CyclomaticComplexity:
  Max: 1000000
Metrics/AbcSize:
  Max: 1000000
Metrics/ModuleLength:
  Max: 1000000
Style/GlobalVars:
  Enabled: false
